GHA validator (#3)
* add

* fix

* add annotations

* add job-summary

* fix

diff --git a/.github/workflows/template.yml b/.github/workflows/template.yml
--- a/.github/workflows/template.yml
+++ b/.github/workflows/template.yml
@@ -20,7 +20,16 @@ env:
   EXAMPLE: example
   REPO_VAR: ${{ vars.REPO_VAR}}
   REPO_SECRET: ${{ secrets.REPO_SECRET }}
-
+# デフォルトシェル
+# 未設定の場合： bash -e {0}
+# 設定の場合： bash --noprofile --norc -eo pipefail {0}
+defaults:
+  run:
+    shell: bash
+# 並行実行の設定. 特にon:pull_reuqestの場合は必須
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   # Workflowレベルで環境変数を使用する方法
   env-with-workflow:
@@ -72,3 +81,18 @@ jobs:
       - run: gh pr comment ${{ github.event.pull_request.number }} --body "Hello, World!"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  annotations:
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo "::error::This is an error"
+      - run: echo "::warning::This is a warning"
+      - run: echo "::notice::This is a notice"
+  job-summary:
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          {
+            echo "## Example Title :rocket:"
+            echo "- first line"
+            echo "- second line"
+          } >> "${GITHUB_STEP_SUMMARY}"
